### ISSUE TITLE
Validating multi-cpu fail

### ISSUE THREAD

**Issue by yillkid** [DLTcollab/dcurl#46]
reproduce:
```shell
$ make check
*** Validating build/test-trinary ***
	[ Verified ]
*** Validating build/test-curl ***
	[ Verified ]
*** Validating build/test-pow_sse ***
	[ Verified ]
*** Validating build/test-multi_pow_cpu ***
mk/common.mk:27: recipe for target 'build/test-multi_pow_cpu.done' failed
make: *** [build/test-multi_pow_cpu.done] Error 1```

environment:
```shell
$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.4.0-6ubuntu1~16.04.9' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.9) 
$ uname -a
Linux Orz 4.4.0-124-generic #148-Ubuntu SMP Wed May 2 13:00:18 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by jserv** [comment]
Use the following syntax to re-indent your messages:
```
    ```shell
    text area
    ```
```
Otherwise, it is not straightforward to look around.

**Comment by berrytchaks** [comment]
Hi, I'm going through a similar issue.
Reproduce:
Install the opencl SDK from https://software.intel.com/en-us/intel-opencl

$ make BUILD_GPU=0 BUILD_JNI=1 BUILD_AVX=1
  CC	build/curl.o
  CC	build/constants.o
  CC	build/trinary.o
  CC	build/dcurl.o
  CC	build/pow_avx.o
src/pow_avx.c: In function ‘pworkThread’:
src/pow_avx.c:470:31: warning: pointer targets in passing argument 1 of ‘pwork256’ differ in signedness [-Wpointer-sign]
     pworkInfo->ret = pwork256(pworkInfo->mid, pworkInfo->mwm, pworkInfo->nonce,
                               ^
src/pow_avx.c:241:16: note: expected ‘char *’ but argument is of type ‘int8_t * {aka signed char *}’
 static int64_t pwork256(char mid[], int mwm, char nonce[], int n, int id)
                ^
src/pow_avx.c:470:63: warning: pointer targets in passing argument 3 of ‘pwork256’ differ in signedness [-Wpointer-sign]
     pworkInfo->ret = pwork256(pworkInfo->mid, pworkInfo->mwm, pworkInfo->nonce,
                                                               ^
src/pow_avx.c:241:16: note: expected ‘char *’ but argument is of type ‘int8_t * {aka signed char *}’
 static int64_t pwork256(char mid[], int mwm, char nonce[], int n, int id)
                ^
  CURL	build/com/iota/iri/hash/PearlDiver.java
  JAVAH	build/jni/iri-pearldiver-exlib.h
  CC	build/jni/iri-pearldiver-exlib.o
  CC	build/test-trinary.o
  LD	build/test-trinary
  CC	build/test-curl.o
  LD	build/test-curl
  CC	build/test-pow_avx.o
  LD	build/test-pow_avx
  LD	build/libdcurl.so
Makefile:135: "skip build/test-multi_pow_cpu because PyIOTA is not installed."
rm build/test-trinary.o build/test-curl.o build/test-pow_avx.o

$ make BUILD_GPU=1 check
  CC	build/pow_sse.o
  CC	build/pow_cl.o
  CC	build/clcontext.o
src/clcontext.c: In function ‘init_cl_devices’:
src/clcontext.c:56:5: warning: ‘clCreateCommandQueue’ is deprecated [-Wdeprecated-declarations]
     ctx->cmdq = clCreateCommandQueue(ctx->context, ctx->device, 0, &errno);
     ^
In file included from src/clcontext.h:13:0,
                 from src/clcontext.c:8:
/usr/include/CL/cl.h:1428:1: note: declared here
 clCreateCommandQueue(cl_context                     /* context */,
 ^
  CC	build/test-trinary.o
  LD	build/test-trinary
*** Validating build/test-trinary ***
	[ Verified ]
  CC	build/test-curl.o
  LD	build/test-curl
*** Validating build/test-curl ***
	[ Verified ]
  CC	build/test-pow_sse.o
  LD	build/test-pow_sse
*** Validating build/test-pow_sse ***
	[ Verified ]
  LD	build/libdcurl.so
Makefile:135: "skip build/test-multi_pow_cpu because PyIOTA is not installed."
*** Validating build/test-multi_pow_cpu ***
	[ Verified ]
  CC	build/test-pow_cl.o
  LD	build/test-pow_cl
*** Validating build/test-pow_cl ***
Segmentation fault (core dumped)
mk/common.mk:27: recipe for target 'build/test-pow_cl.done' failed
make: *** [build/test-pow_cl.done] Error 139
rm build/test-trinary.o build/test-curl.o build/test-pow_sse.o build/test-pow_cl.o

$ uname -a
Linux london202 4.4.0-127-generic #153-Ubuntu SMP Sat May 19 10:58:46 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.4.0-6ubuntu116.04.9' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.9) 

Was anybody able to solve this?

**Comment by furuame** [comment]
@berrytchaks I think this is different issue, I will take it a look in these days :)

btw, does your machine have gpu card?

**Comment by berrytchaks** [comment]
Thanks for replying. Yes my machine has a gpu card. Please let me know if
you need any additional information.

**Comment by furuame** [comment]
@berrytchaks Please also give me how do you set `mk/opencl.mk`?

Could you use gdb and tell me which line trigger segmentation fault?

**Comment by jserv** [comment]
@berrytchaks reported OpenCL validation problem. However, @yillkid originally asked for multiple cpu implementation, which should work out of box. Close first and work on further OpenCL issues.
