### ISSUE TITLE
Use cases about adoption

### ISSUE THREAD

**Issue by jserv** [DLTcollab/dcurl#67]
Although dcurl was not meant to be a major component in IOTA ecosystem, it is still vital for developers who wish to introduce various hardware accelerations by means of dcurl interface. There are already some preliminary users of dcurl, and it would be nice if we can mention them in top-level documentation.

**Comment by tylerw1369** [comment]
I am trying to build a pow nodes for iota with my de10 nano using dcurl and if I am successful at it I will let you guys know so you can mention it. I obviously plan to get a webpage set up for north american users so that they have a place to develop. My plan is to have nodes behind my load balancer and use my de10 nanos as pow nodes.  I will mention all of the help dcurl has been in order to get it up and running if you guys are ok with that. Im not very good with code so I am learning the best way possible to create my pow node software that runs on my de10 nano.

**Comment by jserv** [comment]
@tylerw1369, I'm excited to hear your messages about DE10-Nano Kit. Feel free to share your story here, and @ajblane will follow and make some suggestions.
