### ISSUE TITLE
Potential undefined behaviour in pow_avx.c

### ISSUE THREAD

**Issue by wusyong** [DLTcollab/dcurl#89]
There's an undefined behaviour in pow_avx.c when performing static code analysis using cppcheck:

```
undefined behaviour in pow_avx.c
[third_party/dcurl/src/pow_avx.c:329]: (error) Shifting signed 64-bit value by 63 bits is undefined behaviour
```

Not sure if it's false positive.

**Comment by marktwtn** [comment]
In `pow_avx.h`, there is a defined `union` **dl** for the platform which does not support `avx2` instruction set.

```
typedef union {
    double d;
    unsigned long long l;
} dl;
```

And the variable assignment is
```
long long np = ((dl) nonce_probe[j]).l; 
```

Please change the `long long` to `unsigned long long` and check again.
And are other files like `pow_c.c` and `pow_sse.c` are checked, too?
How about on the platform which supports `avx2` instruction set?

To test `avx` and `avx2` is annoying, since the current implementation would choose `avx2` automatically if the hardware supports it.
To test the `avx` part, we have to find the hardware platform which does not support `avx2` but only `avx`.
But perhaps the **static** code analysis would not have to worry about this?

If the code analysis has no problem, please notify me and I'll send a pull request.

**Comment by jserv** [comment]
How about replacing `long long` with explicit type(s) in `<stdint.h>`?

**Comment by marktwtn** [comment]
> How about replacing `long long` with explicit type(s) in `<stdint.h>`?

That would be `uint64_t`.
@wusyong please use it instead.

**Comment by marktwtn** [comment]
According to @wusyong , all the files are checked and replacing data type with `uint64_t` fixes the error.

I would like to check whether there are similar data type mismatching or not.

**Comment by jserv** [comment]
Before closing this issue, please write down the lesson we have learnt for further study.

**Comment by marktwtn** [comment]
After changing to the `uint64_t`, the compile error has occurred.
```
error: cast to union type from type not present in union
```
The literal constant (ex: 0xFFFFFFFFFFFFFFFFull) is indicated with `uLL`, which means `unsigned long long`.
And according to the `GCC` document:
```
The types that may be cast to the union type are those of the members of the union.
```

It turns out that the data type `uint64_t` equals to `unsigned long` but not equals to `unsigned long long`.
Keep investigating.

**Comment by jserv** [comment]
Replace "is equal to" with "equals to" for syntax.

**Comment by marktwtn** [comment]
First of all, **cast to union** is not in ISO standard C.
It is treated as an extension supported by **GCC**.
Ref: [C Extensions](https://gcc.gnu.org/onlinedocs/gcc-7.4.0/gcc/C-Extensions.html#C-Extensions)

The way to use **cast to union** can be found in this [document](https://gcc.gnu.org/onlinedocs/gcc-7.4.0/gcc/Cast-to-Union.html#Cast-to-Union).
It says:
```
The types that may be cast to the union type are those of the members of the union.
```

It is a rigid rule. No data type promotion is allowed.
For example:
```
typedef union {
    long a;
    double b;
} UNION;

int x = 3;
double c = ((UNION)x).b;
```
The compilation would fail unless the data type of `x` is changed from `int` to `long`.

If the data types have the same size and do not equal to each other,
the compilation would fail either.
For example:
`uint64_t` and `unsigned long long` on 64-bit data model `LP64` with `glibc`.

---

On 32-bit architecture, `uint64_t` equals to `unsigned long long`.
On 64-bit architecture, `uint64_t` equals to `unsigned long`.
The source code of `glibc` <stdint.h>
```
#if __WORDSIZE == 64
typedef signed long int __int64_t;
typedef unsigned long int __uint64_t;
#else
__extension__ typedef signed long long int __int64_t;
__extension__ typedef unsigned long long int __uint64_t;
#endif
```

To solve the problem, just make sure the literal constant is indicated as `unsigned long` (0x...UL).

However, I was wondering that maybe we should **use the original `unsigned long long` instead of changing it to `uint64_t` in `union`**?
Since the `unsigned long long` of different [64-bit data model](https://en.wikipedia.org/wiki/64-bit_computing#64-bit_data_models) are always 64-bit width.
I just concerned about the possibility (different architecture or OS) that `uint64_t` does not equal to `unsigned long` and causes the compile error again.
Using `unsigned long long` data type in `union` would make sure everything goes right.

Any suggestion or advise?

**Comment by marktwtn** [comment]
Here are two problems:

1. The original problem detected by `cppcheck`.
Sorry for my previous wrong explanation.
The correct one is:

    **It has nothing to do with the `union` `dl` defined in `pow_avx.h` at all**.

    In normal use case, `Shifting signed 64-bit value by 63 bits` might cause some problems.
The leftmost bit is used for indicating whether the signed value is positive or negative.

    However, in our case we just shift the variable and do the `&` operation with value 1.
It is just a single bit comparison. Whether the variable is signed or unsigned would not affect the result.
The program still works well.

    **Conclusion: The problem detected by `cppcheck` do not cause any problem at all.**
But I still prefer using `unsigned long long` for data type matching and eliminating the `cppcheck` error.

2. Use `uint64_t` instead of `unsigned long long`.
Since `cast to union` is rigid and according to the last comment, I might prefer not to replace it with `uint64_t` data type.

**Comment by jserv** [comment]
If we can clarify false negative pointed by `cppcheck`, we can safely ignore it. I agree with the way to stick with `unsigned long long`.

**Comment by marktwtn** [comment]
The issue can be closed since the detected undefined behaviour does not cause any problem.
