### ISSUE TITLE
Remote PoW service to manipulate queued requests

### ISSUE THREAD

**Issue by jserv** [DLTcollab/dcurl#91]
At the moment, `dcurl` already provides preliminary FPGA acceleration with consistent APIs, which enable transparent switching among SIMD, OpenCL, and FPGA implementations. However, it is not straightforward to accelerate existing IRI instances with FPGA accelerations because of the interoperability. Thus, we shall provide a remote PoW service dedicated to queued requests as [PoWbox](https://blog.iota.org/relaunching-the-powbox-d392236b6939) does.

Expected output:
1. Use existing libraries, such as ZeroMQ and ProtocolBuffer, to marshal / serialize the PoW operations;
2. Provide client-side interface to access FPGA-accelerated machines. Cyclone V-based device is the preferable target;
3. Verify IRI or Tangle-Accelerator + dcurl integration with FPGA accelerations;

Reference:
1. [PoWbox](https://github.com/iotaledger/powbox)
2. [diverDriver](https://github.com/muXxer/diverDriver)

**Comment by tylerw1369** [comment]
If you need help testing let me know I can on my nano.  I can even allow you access to my nano if needed

**Comment by jserv** [comment]
However, I am a bit afraid that PoWbox might be too heavy to launch on devices powered by Cyclone V. [powsrv](https://gitlab.com/powsrv.io) just implements slim interface with protocol buffers.

**Comment by ajblane** [comment]
client-side interface is expected as follows:

* remote_interface_init()
check rabbitmq broker is alive

* remote_interface_create_pow_work()
asynchronously send transaction and mwm to rabbitmq broker

* remotre_interface_get_pow_result()
asynchronously get result from rabbitmq broker

* remote_interface_destroy()
leave rabbitmq broker

Issues:
1. When client-side requests are too many, we can build and manage more than one rabbitmq broker.
2. Need test bulk transfer effort

**Comment by ajblane** [comment]
For managing RabbitMQ broker, RabbitMQ provides management plugin, names [rabbitmq_management](https://www.rabbitmq.com/management.html). It's very friendly and can show internal information. We need to be familiar with [rabbitmq_management](https://www.cloudamqp.com/blog/2015-05-27-part3-rabbitmq-for-beginners_the-management-interface.html) to manage it.

**Comment by ajblane** [comment]
> However, I am a bit afraid that PoWbox might be too heavy to launch on devices powered by Cyclone V. powsrv just implements slim interface with protocol buffers.

We only require RabbitMQ C client library on devices.

**Comment by ajblane** [comment]
As [AMQP 0-9-1 Model](https://www.rabbitmq.com/tutorials/amqp-concepts.html), it can support [patterns](https://www.rabbitmq.com/getstarted.html) by setting exchange and route in AMQP 0-9-1 Model:
* Work queues
* Publish/subscribe
* Routing
* Request/reply (RPC)

[IOTA's powbox](https://github.com/iotaledger/powbox) uses AMQP 0-9-1 Model to implement a remote server to asynchronously do PoW and it deploys [a kubernetes cluster including a client, a broker and a worker](https://github.com/iotaledger/powbox/tree/develop/deploy). For IRI with IOTA's powbox, an IRI uses a kubernetes cluster. Therefore, there is no problem for order number.

This PR, [https://github.com/DLTcollab/dcurl/pull/117](https://github.com/DLTcollab/dcurl/pull/117), it is inspired by IOTA's powbox. However, currently, if this PR is used in scenario of multi-clients, multi-workers and a broker, there is a problem of order number because multi-workers do not orderly publish results to the completed queue.  For order number problem of the PR, I propose two methods to discuss them. 

**Method 1:** A remote interface library for a client only can bind a message queue pair (incoming queue/ completed queue) in a broker and a worker.

**Method 2:** A remote interface library for a client only can bind a message queue pair (incoming queue/ completed queue) in a broker and multi-workers. 

Both method 1 and 2, they need to be considered about how many message queue pairs a broker does not exceed the memory limitation. 

On the other hand, method 2 needs to consider order number problem, the remote interface library needs to set message order when publishing the message into the broker and implement a buffer for order messages when consuming the completed buffer.

For easy implementations, I prefer to use the method 1.

**Comment by ajblane** [comment]
For the test method of this PR, [https://github.com/DLTcollab/dcurl/pull/117](https://github.com/DLTcollab/dcurl/pull/117), it currently is not easy for test. Therefore, we plan to provide RabbitMQ API hooks for testing dcurl worker and remote interface.

**Comment by ajblane** [comment]
For troubleshooting of using RabbitMQ APIs, we can refer to [this issue](https://github.com/alanxz/rabbitmq-c/issues/469), [amqp_rpc_reply_t](https://github.com/alanxz/rabbitmq-c/blob/009bc4df22065d44e894d69c42aead4881ab6ca4/librabbitmq/amqp.h#L648), [amqp_status_enum](https://github.com/alanxz/rabbitmq-c/blob/009bc4df22065d44e894d69c42aead4881ab6ca4/librabbitmq/amqp.h#L771) and [amqp_error_string2](https://github.com/alanxz/rabbitmq-c/blob/550f4c56562baf2dc1c6c6b6285b4fd13fa0097c/librabbitmq/amqp.h#L2102) to print information when trouble.

**Comment by jserv** [comment]
There is no real "easy implementation". Instead, it can be "straightforward" or "naive" from the perspective of architecture design.

**Comment by ajblane** [comment]
In this article, ["Asynchronous Messaging Primer"](https://docs.microsoft.com/en-us/previous-versions/msp-n-p/dn589781(v=pandp.10)),  basic message queuing patterns are listed below:
* One-way messaging
* Request/response messaging
* Broadcast messaging

For using ZeroMQ (zero broker/ zero latency ) to implement the request/response messaging pattern for FPGA boards as multi-workers,  it needs to implement a broker. About how to implement it, we can refer to this article, ["Robust Reliable Queuing (Paranoid Pirate Pattern)"](http://zguide.zeromq.org/page:all#Robust-Reliable-Queuing-Paranoid-Pirate-Pattern).  However, we do not need to implement the broker by using RabbitMQ. 

Moreover,  whether we use ZeroMQ or RabbitMQ, we need to implement a solution  for the order in which the client receives PoW result messages in scenario of multi-workers in the asynchronous messaging pattern. However, in the article ["Robust Reliable Queuing (Paranoid Pirate Pattern)"](http://zguide.zeromq.org/page:all#Robust-Reliable-Queuing-Paranoid-Pirate-Pattern), the method of using synchronous request and asynchronous reply is used to guarantee that the client will never get an out-of-order reply.

By contrast, I prefer to use RabbitMQ. By the way, in a scenario for the broker and workers to run on a machine, we can refer to this article, ["The Asynchronous Client/Server Pattern"](http://zguide.zeromq.org/page:all#The-Asynchronous-Client-Server-Pattern), to implement no broker by using ZeroMQ to reach lower latency. For using FPGA boards as workers, the scenario of no broker is not matched.

**Comment by ajblane** [comment]
Related to https://github.com/DLTcollab/dcurl/issues/127

**Comment by ajblane** [comment]
Related to [#133](https://github.com/DLTcollab/dcurl/issues/133)

**Comment by ajblane** [comment]
Related to [#137](https://github.com/DLTcollab/dcurl/issues/137)

**Comment by ajblane** [comment]
Related to [#139](https://github.com/DLTcollab/dcurl/issues/139)

**Comment by ajblane** [comment]
Related to https://github.com/DLTcollab/dcurl/issues/146

**Comment by ajblane** [comment]
Related to #151

**Comment by ajblane** [comment]
Related to #152
